spring:
  port: 8080
  datasource:
    url: jdbc:mysql://localhost:3307/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root599926
  mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.javademo.bean
    configuration:
      map-underscore-to-camel-case: true